### ISSUE TITLE
API reference is 404

### ISSUE THREAD

**Issue by FabioM3** [VasilKalchev/LiquidMenu#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Library version

Yes, from GitHub's "master" branch.

### Bug description

The link to the API reference in main doc is 404.

**Comment by shahmirthesquid** [comment]
I also am having this issue 😢 I wanted to learn how to use this library for my project but cannot access the documentation

**Comment by ur4ltz** [comment]
Use this URL.

https://vasilkalchev.github.io/LiquidMenu/annotated.html
