### ISSUE TITLE
Date string `char*`

### ISSUE THREAD

**Issue by lu6fer** [VasilKalchev/LiquidMenu#13]
Hello,
I want to use date Time string on the welcom screenshots. I get this date/Time from rtc library(DS3231) and convert it to a char*[20] but it doesnt display.
The same datestring is correctly displayed with LCD.print()

**Comment by VaSe7u** [comment]
Your argument should be a pointer to a char array:

```
char myCharArray[20] = "char array";
char *myCharArray_ptr = myCharArray;
LiquidLine line1(1, 0, myCharArray_ptr);
```


If that doesn't help, can you post the part of your code that deals with the char array and a link to the library you are using?
