### ISSUE TITLE
Variable string does not display correctly when used as LiquidLine parameter

### ISSUE THREAD

**Issue by joshfeliciano** [VasilKalchev/LiquidMenu#4]
See title

**Comment by VasilKalchev** [comment]
I will be able to test the problem in 5 days.

**Comment by VasilKalchev** [comment]
Sorry for the huge delay.

Use `char*` for a changing string:
```
char* varString= "State 1";
LiquidLine line1(0, 0, varString);
...
varString = "State 2";
```
You can cast the string literal to `(char*)` to avoid the warning.

**Comment by joshfeliciano** [comment]
Thanks much!

**Comment by Fluxia0** [comment]
hello 
Arduino's compiler seem to complain when doing this : 
"_deprecated conversion from string constant to 'char*' [-Wwrite-strings] char* varString= "State 1";"_
Also I have tried using a pointer to const chars but the strings do not display correctly in the LCD.

**Comment by VaSe7u** [comment]
Casting the string literal to `(char*)` (e.g. `char* varString = (char*)"State 1";`) should hide the warning.
A more correct way would be to assign the pointer to a char array in memory.
